version: "3.9"
services:

  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    user: root
    restart:
      unless-stopped
    volumes:
      - ./deploy/files:/home/app/documents
    ports:
      - "9024:9024"